[package]
name = "p2019_22"
version = "0.1.0"
authors = ["Joshua Netterfield <joshua@nettek.ca>"]
edition = "2018"

[dependencies]
modinverse = "0.1.1"
modexp = "0.2.2"
num-integer = "*"
num-traits = "*"
